[platformio]
default_envs = esp32dev

[common]
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = default_16MB.csv
board_build.mcu = esp32
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.f_flash = 80000000L

monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time

lib_deps =
    adafruit/Adafruit SH110X@^2.1.10
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit BusIO@^1.16.1
    bblanchon/ArduinoJson@^7.3.0

build_flags = ${common.build_flags}

debug_build_flags =
    -DDEBUG_ESP_PORT=Serial
    -DDEBUG_ESP_WIFI
    -DDEBUG_ESP_HTTP_CLIENT

[env:esp32dev-debug]
extends = env:esp32dev
build_type = debug
build_flags = ${common.build_flags} ${debug_build_flags}
