// <auto-generated />
using System;
using Klippyface.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Klippyface.Server.Data.Migrations
{
    [DbContext(typeof(KlippyfaceDbContext))]
    [Migration("20261006092715_AddDescriptionsAndSpriteFolders")]
    partial class AddDescriptionsAndSpriteFolders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Klippyface.Server.Models.Assignment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivePreset")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivePreset");

                    b.HasIndex("DisplayId")
                        .IsUnique();

                    b.HasIndex("NodeId", "DisplayId")
                        .IsUnique();

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("Klippyface.Server.Models.Frame", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BgColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.ToTable("Frames");
                });

            modelBuilder.Entity("Klippyface.Server.Models.FrameElement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FrameId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FrameId");

                    b.ToTable("FrameElements");
                });

            modelBuilder.Entity("Klippyface.Server.Models.Group", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Klippyface.Server.Models.Node", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("LastConfigVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MacAddress")
                        .IsUnique();

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("Klippyface.Server.Models.NodeDisplay", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusConfig")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BusType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rotation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("NodeDisplays");
                });

            modelBuilder.Entity("Klippyface.Server.Models.NodePreset", b =>
                {
                    b.Property<string>("NodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PresetId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("NodeId", "PresetId");

                    b.HasIndex("PresetId");

                    b.ToTable("NodePresets");
                });

            modelBuilder.Entity("Klippyface.Server.Models.Preset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OverridesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Presets");
                });

            modelBuilder.Entity("Klippyface.Server.Models.Set", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FrameTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LoopCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("Klippyface.Server.Models.Sprite", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataBase64")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Sprites");
                });

            modelBuilder.Entity("Klippyface.Server.Models.Assignment", b =>
                {
                    b.HasOne("Klippyface.Server.Models.Preset", "Preset")
                        .WithMany()
                        .HasForeignKey("ActivePreset")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Klippyface.Server.Models.NodeDisplay", "Display")
                        .WithOne("Assignment")
                        .HasForeignKey("Klippyface.Server.Models.Assignment", "DisplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Klippyface.Server.Models.Node", "Node")
                        .WithMany("Assignments")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Display");

                    b.Navigation("Node");

                    b.Navigation("Preset");
                });

            modelBuilder.Entity("Klippyface.Server.Models.Frame", b =>
                {
                    b.HasOne("Klippyface.Server.Models.Set", "Set")
                        .WithMany("Frames")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("Klippyface.Server.Models.FrameElement", b =>
                {
                    b.HasOne("Klippyface.Server.Models.Frame", "Frame")
                        .WithMany("Elements")
                        .HasForeignKey("FrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frame");
                });

            modelBuilder.Entity("Klippyface.Server.Models.NodeDisplay", b =>
                {
                    b.HasOne("Klippyface.Server.Models.Node", "Node")
                        .WithMany("Displays")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Klippyface.Server.Models.NodePreset", b =>
                {
                    b.HasOne("Klippyface.Server.Models.Node", "Node")
                        .WithMany("NodePresets")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Klippyface.Server.Models.Preset", "Preset")
                        .WithMany("NodePresets")
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("Preset");
                });

            modelBuilder.Entity("Klippyface.Server.Models.Set", b =>
                {
                    b.HasOne("Klippyface.Server.Models.Group", "Group")
                        .WithMany("Sets")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Klippyface.Server.Models.Frame", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("Klippyface.Server.Models.Group", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("Klippyface.Server.Models.Node", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Displays");

                    b.Navigation("NodePresets");
                });

            modelBuilder.Entity("Klippyface.Server.Models.NodeDisplay", b =>
                {
                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("Klippyface.Server.Models.Preset", b =>
                {
                    b.Navigation("NodePresets");
                });

            modelBuilder.Entity("Klippyface.Server.Models.Set", b =>
                {
                    b.Navigation("Frames");
                });
#pragma warning restore 612, 618
        }
    }
}
