// <auto-generated />
using System;
using Klippyface.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Klippyface.Server.Data.Migrations
{
    [DbContext(typeof(KlippyfaceDbContext))]
    partial class KlippyfaceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Klippyface.Server.Models.Assignment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivePreset")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivePreset");

                    b.HasIndex("DisplayId")
                        .IsUnique();

                    b.HasIndex("NodeId", "DisplayId")
                        .IsUnique();

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = "d4e5f6a7-b8c9-0123-defa-234567890123",
                            DefaultGroup = "idle_faces",
                            DisplayId = "b2c3d4e5-f6a7-8901-bcde-f12345678901",
                            NodeId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            TriggersJson = "{\"state:printing\":\"printing_faces\",\"state:complete\":\"celebration_faces\",\"state:error\":\"error_faces\",\"state:idle\":\"idle_faces\",\"state:paused\":\"paused_faces\",\"state:waiting\":\"waiting_faces\",\"macro:print_start\":\"printing_faces\",\"macro:print_end\":\"celebration_faces\"}"
                        },
                        new
                        {
                            Id = "e5f6a7b8-c9d0-1234-efab-345678901234",
                            DefaultGroup = "stats_idle",
                            DisplayId = "c3d4e5f6-a7b8-9012-cdef-123456789012",
                            NodeId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            TriggersJson = "{\"state:printing\":\"stats_progress\",\"state:complete\":\"stats_done\",\"state:idle\":\"stats_idle\"}"
                        });
                });

            modelBuilder.Entity("Klippyface.Server.Models.Frame", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BgColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.ToTable("Frames");

                    b.HasData(
                        new
                        {
                            Id = "b8c9d0e1-f2a3-4567-bcde-678901234567",
                            BgColor = "#000000",
                            DurationMs = 3000,
                            SetId = "f6a7b8c9-d0e1-2345-fabc-456789012345",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "c9d0e1f2-a3b4-5678-cdef-789012345678",
                            BgColor = "#000000",
                            DurationMs = 200,
                            SetId = "f6a7b8c9-d0e1-2345-fabc-456789012345",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "d0e1f2a3-b4c5-6789-defa-890123456789",
                            BgColor = "#000000",
                            DurationMs = 600,
                            SetId = "a7b8c9d0-e1f2-3456-abcd-567890123456",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "e1f2a3b4-c5d6-7890-efab-901234567890",
                            BgColor = "#000000",
                            DurationMs = 600,
                            SetId = "a7b8c9d0-e1f2-3456-abcd-567890123456",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "f2a3b4c5-d6e7-8901-fabc-012345678901",
                            BgColor = "#000000",
                            DurationMs = 600,
                            SetId = "a7b8c9d0-e1f2-3456-abcd-567890123456",
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("Klippyface.Server.Models.FrameElement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FrameId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FrameId");

                    b.ToTable("FrameElements");

                    b.HasData(
                        new
                        {
                            Id = "a3b4c5d6-e7f8-9012-abcd-123456789012",
                            Color = "#FFFFFF",
                            FrameId = "b8c9d0e1-f2a3-4567-bcde-678901234567",
                            Label = "",
                            SortOrder = 0,
                            Type = "text",
                            Value = "zzz",
                            X = 64,
                            Y = 32
                        },
                        new
                        {
                            Id = "b4c5d6e7-f8a9-0123-bcde-234567890123",
                            Color = "#FFFFFF",
                            FrameId = "c9d0e1f2-a3b4-5678-cdef-789012345678",
                            Label = "",
                            SortOrder = 0,
                            Type = "sprite",
                            Value = "blink",
                            X = 64,
                            Y = 32
                        },
                        new
                        {
                            Id = "c5d6e7f8-a9b0-1234-cdef-345678901234",
                            Color = "#FFFFFF",
                            FrameId = "d0e1f2a3-b4c5-6789-defa-890123456789",
                            Label = "",
                            SortOrder = 0,
                            Type = "sprite",
                            Value = "face_happy",
                            X = 64,
                            Y = 32
                        },
                        new
                        {
                            Id = "d6e7f8a9-b0c1-2345-defa-456789012345",
                            Color = "#FFFFFF",
                            FrameId = "e1f2a3b4-c5d6-7890-efab-901234567890",
                            Label = "",
                            SortOrder = 0,
                            Type = "sprite",
                            Value = "face_excited",
                            X = 64,
                            Y = 32
                        },
                        new
                        {
                            Id = "e7f8a9b0-c1d2-3456-efab-567890123456",
                            Color = "#FFFFFF",
                            FrameId = "f2a3b4c5-d6e7-8901-fabc-012345678901",
                            Label = "",
                            SortOrder = 0,
                            Type = "sprite",
                            Value = "face_wow",
                            X = 64,
                            Y = 32
                        });
                });

            modelBuilder.Entity("Klippyface.Server.Models.Group", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = "idle_faces",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Label = "Idle Faces",
                            SortOrder = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "printing_faces",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Label = "Printing Faces",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Klippyface.Server.Models.Node", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MacAddress")
                        .IsUnique();

                    b.ToTable("Nodes");

                    b.HasData(
                        new
                        {
                            Id = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Main 3D printer display",
                            FriendlyName = "Printer Face",
                            MacAddress = "AA:BB:CC:DD:EE:01",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Klippyface.Server.Models.NodeDisplay", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusConfig")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BusType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rotation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("NodeDisplays");

                    b.HasData(
                        new
                        {
                            Id = "b2c3d4e5-f6a7-8901-bcde-f12345678901",
                            BusConfig = "{\"address\":\"0x3C\"}",
                            BusType = "i2c",
                            DriverType = "sh1106",
                            Height = 64,
                            Label = "Front Face",
                            NodeId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            Rotation = 0,
                            SortOrder = 0,
                            Width = 128
                        },
                        new
                        {
                            Id = "c3d4e5f6-a7b8-9012-cdef-123456789012",
                            BusConfig = "{\"address\":\"0x3D\"}",
                            BusType = "i2c",
                            DriverType = "sh1106",
                            Height = 64,
                            Label = "Info Panel",
                            NodeId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            Rotation = 0,
                            SortOrder = 1,
                            Width = 128
                        });
                });

            modelBuilder.Entity("Klippyface.Server.Models.NodePreset", b =>
                {
                    b.Property<string>("NodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PresetId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("NodeId", "PresetId");

                    b.HasIndex("PresetId");

                    b.ToTable("NodePresets");
                });

            modelBuilder.Entity("Klippyface.Server.Models.Preset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OverridesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Presets");
                });

            modelBuilder.Entity("Klippyface.Server.Models.Set", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("FrameTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LoopCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Sets");

                    b.HasData(
                        new
                        {
                            Id = "f6a7b8c9-d0e1-2345-fabc-456789012345",
                            FrameTime = 0,
                            GroupId = "idle_faces",
                            Label = "Sleepy",
                            LoopCount = 0,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "a7b8c9d0-e1f2-3456-abcd-567890123456",
                            FrameTime = 600,
                            GroupId = "printing_faces",
                            Label = "Excited",
                            LoopCount = 0,
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("Klippyface.Server.Models.Sprite", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataBase64")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Sprites");

                    b.HasData(
                        new
                        {
                            Id = "blink",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataBase64 = "",
                            Height = 16,
                            Label = "Blink",
                            Width = 16
                        },
                        new
                        {
                            Id = "face_happy",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataBase64 = "",
                            Height = 64,
                            Label = "Face Happy",
                            Width = 64
                        },
                        new
                        {
                            Id = "face_excited",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataBase64 = "",
                            Height = 64,
                            Label = "Face Excited",
                            Width = 64
                        },
                        new
                        {
                            Id = "face_wow",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataBase64 = "",
                            Height = 64,
                            Label = "Face Wow",
                            Width = 64
                        });
                });

            modelBuilder.Entity("Klippyface.Server.Models.Assignment", b =>
                {
                    b.HasOne("Klippyface.Server.Models.Preset", "Preset")
                        .WithMany()
                        .HasForeignKey("ActivePreset")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Klippyface.Server.Models.NodeDisplay", "Display")
                        .WithOne("Assignment")
                        .HasForeignKey("Klippyface.Server.Models.Assignment", "DisplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Klippyface.Server.Models.Node", "Node")
                        .WithMany("Assignments")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Display");

                    b.Navigation("Node");

                    b.Navigation("Preset");
                });

            modelBuilder.Entity("Klippyface.Server.Models.Frame", b =>
                {
                    b.HasOne("Klippyface.Server.Models.Set", "Set")
                        .WithMany("Frames")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("Klippyface.Server.Models.FrameElement", b =>
                {
                    b.HasOne("Klippyface.Server.Models.Frame", "Frame")
                        .WithMany("Elements")
                        .HasForeignKey("FrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frame");
                });

            modelBuilder.Entity("Klippyface.Server.Models.NodeDisplay", b =>
                {
                    b.HasOne("Klippyface.Server.Models.Node", "Node")
                        .WithMany("Displays")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Klippyface.Server.Models.NodePreset", b =>
                {
                    b.HasOne("Klippyface.Server.Models.Node", "Node")
                        .WithMany("NodePresets")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Klippyface.Server.Models.Preset", "Preset")
                        .WithMany("NodePresets")
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("Preset");
                });

            modelBuilder.Entity("Klippyface.Server.Models.Set", b =>
                {
                    b.HasOne("Klippyface.Server.Models.Group", "Group")
                        .WithMany("Sets")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Klippyface.Server.Models.Frame", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("Klippyface.Server.Models.Group", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("Klippyface.Server.Models.Node", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Displays");

                    b.Navigation("NodePresets");
                });

            modelBuilder.Entity("Klippyface.Server.Models.NodeDisplay", b =>
                {
                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("Klippyface.Server.Models.Preset", b =>
                {
                    b.Navigation("NodePresets");
                });

            modelBuilder.Entity("Klippyface.Server.Models.Set", b =>
                {
                    b.Navigation("Frames");
                });
#pragma warning restore 612, 618
        }
    }
}
